# Сборка бинарного файла
FROM golang:1.25-alpine AS builder

WORKDIR /app

# Копируем зависимости для кэширования
COPY go.mod go.sum ./
RUN go mod download

# Копируем только необходимые файлы для компиляции
COPY .env config ./cmd ./internal ./go.run .

# Проверяем целостность зависимостей
RUN go mod verify

# Статическая компиляция без CGO
RUN CGO_ENABLED=0 GOOS=linux \
    go build -o /chat-server ./cmd/server

# Минимальный финальный образ
FROM alpine:3.18

# Устанавливаем минимальные зависимости
RUN apk --no-cache add ca-certificates tzdata

WORKDIR /app

# Переносим артефакты из builder-стадии
COPY --from=builder /chat-server .
COPY --from=builder /app/config ./config

# Настройка порта и проверка здоровья
EXPOSE 8080
CMD ["./chat-server"]
